--------------------------------------------------------
--  DDL for Table CITIZEN_EVENTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."CITIZEN_EVENTS" 
   (	"EVENT_ID" NUMBER, 
	"EVENT_NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"EVENT_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"GEOM" "SDO_GEOMETRY"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
