--------------------------------------------------------
--  Constraints for Table CSS_PROJECT_TASKS
--------------------------------------------------------

  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("SERIAL" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("SCHEDULE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("PERSONNEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("PERSONNEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("CUSTOMER_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("TASK_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("PROJECT_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."CSS_PROJECT_TASKS" MODIFY ("MODULE_CODE" NOT NULL ENABLE);
