--------------------------------------------------------
--  Constraints for Table DEMO_PAGE_HIERARCHY
--------------------------------------------------------

  ALTER TABLE "PRJ"."DEMO_PAGE_HIERARCHY" ADD CONSTRAINT "DEMO_PAGE_HIERARCHY_PK" PRIMARY KEY ("PAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
