--------------------------------------------------------
--  Constraints for Table FLOW_PROCESS_VARIABLES
--------------------------------------------------------

  ALTER TABLE "PRJ"."FLOW_PROCESS_VARIABLES" ADD CONSTRAINT "PROV_PK" PRIMARY KEY ("PROV_PRCS_ID", "PROV_VAR_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."FLOW_PROCESS_VARIABLES" MODIFY ("PROV_PRCS_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."FLOW_PROCESS_VARIABLES" MODIFY ("PROV_VAR_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."FLOW_PROCESS_VARIABLES" MODIFY ("PROV_VAR_TYPE" NOT NULL ENABLE);
