--------------------------------------------------------
--  Ref Constraints for Table LGS_CONTRACTS
--------------------------------------------------------

  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK1" FOREIGN KEY ("ACCOUNT_MANAGER")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK2" FOREIGN KEY ("PARENT_CONTRACT")
	  REFERENCES "PRJ"."LGS_CONTRACTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK3" FOREIGN KEY ("REF_TO_PIPELINE")
	  REFERENCES "PRJ"."LGS_CONTRACTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK4" FOREIGN KEY ("REF_TO_CONTRACT")
	  REFERENCES "PRJ"."LGS_CONTRACTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK5" FOREIGN KEY ("USAGE_TYPE")
	  REFERENCES "PRJ"."PRJ_LVL_USAGE_TYPE" ("LUT_ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK6" FOREIGN KEY ("OFFER_STATUS")
	  REFERENCES "PRJ"."PRJ_OFFER_STATUS" ("POS_ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK7" FOREIGN KEY ("STATUS")
	  REFERENCES "PRJ"."PRJ_STATUS" ("PST_ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK8" FOREIGN KEY ("INTERNAL_CLASSIFICATION")
	  REFERENCES "PRJ"."PRJ_INTERNAL_CLASSIFICATION" ("PIC_ID") ENABLE;
  ALTER TABLE "PRJ"."LGS_CONTRACTS" ADD CONSTRAINT "LGS_CONTRACTS_FK9" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "PRJ"."LGS_LOGOS_BRANCHES" ("LLB_ID") ENABLE;
