--------------------------------------------------------
--  Constraints for Table LGS_DELETED_PROJECTS
--------------------------------------------------------

  ALTER TABLE "PRJ"."LGS_DELETED_PROJECTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."LGS_DELETED_PROJECTS" MODIFY ("DSP_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."LGS_DELETED_PROJECTS" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."LGS_DELETED_PROJECTS" MODIFY ("MODULE" NOT NULL ENABLE);
