--------------------------------------------------------
--  Constraints for Table LGS_LOGOS_BRANCHES
--------------------------------------------------------

  ALTER TABLE "PRJ"."LGS_LOGOS_BRANCHES" ADD CONSTRAINT "LGS_LOGOS_BRANCHES_PK" PRIMARY KEY ("LLB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."LGS_LOGOS_BRANCHES" MODIFY ("LLB_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."LGS_LOGOS_BRANCHES" MODIFY ("LLB_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."LGS_LOGOS_BRANCHES" MODIFY ("LLB_DESC" NOT NULL ENABLE);
