--------------------------------------------------------
--  Constraints for Table OPP_PRESALE_ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPP_PRESALE_ACTIVITIES" ADD CONSTRAINT "OPP_PRESALE_ACTIVITIES_PK" PRIMARY KEY ("OPA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."OPP_PRESALE_ACTIVITIES" MODIFY ("OPA_ID" NOT NULL ENABLE);
