--------------------------------------------------------
--  Ref Constraints for Table OPP_ACTION_STAKEHOLDERS
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPP_ACTION_STAKEHOLDERS" ADD CONSTRAINT "OPP_ACTION_STAKEHOLDERS_FK1" FOREIGN KEY ("OAS_OAC_ID")
	  REFERENCES "PRJ"."OPP_ACTIONS" ("OAC_ID") ENABLE;
  ALTER TABLE "PRJ"."OPP_ACTION_STAKEHOLDERS" ADD CONSTRAINT "OPP_ACTION_STAKEHOLDERS_FK3" FOREIGN KEY ("OAS_EMPLOYEE")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ENABLE;
