--------------------------------------------------------
--  Ref Constraints for Table OPP_ACTIONS
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPP_ACTIONS" ADD CONSTRAINT "OPP_ACTIONS_FK1" FOREIGN KEY ("OAC_OPP_ID")
	  REFERENCES "PRJ"."OPPORTUNITIES" ("OPP_ID") ENABLE;
  ALTER TABLE "PRJ"."OPP_ACTIONS" ADD CONSTRAINT "OPP_ACTIONS_FK2" FOREIGN KEY ("OAC_OPA_ID")
	  REFERENCES "PRJ"."OPP_PRESALE_ACTIVITIES" ("OPA_ID") ENABLE;
  ALTER TABLE "PRJ"."OPP_ACTIONS" ADD CONSTRAINT "OPP_ACTIONS_FK3" FOREIGN KEY ("OAC_TAKEN_BY")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ENABLE;
