--------------------------------------------------------
--  Ref Constraints for Table OPP_ROLE
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPP_ROLE" ADD CONSTRAINT "OPP_ROLE_FK1" FOREIGN KEY ("ORL_ROL_ID")
	  REFERENCES "PRJ"."ROLES" ("ROL_ID") ENABLE;
  ALTER TABLE "PRJ"."OPP_ROLE" ADD CONSTRAINT "OPP_ROLE_FK2" FOREIGN KEY ("ORL_EMPLOYEE")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ENABLE;
  ALTER TABLE "PRJ"."OPP_ROLE" ADD CONSTRAINT "OPP_ROLE_FK3" FOREIGN KEY ("ORL_OPP_ID")
	  REFERENCES "PRJ"."OPPORTUNITIES" ("OPP_ID") ENABLE;
