--------------------------------------------------------
--  Constraints for Table OPP_STAGES_STATUS
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPP_STAGES_STATUS" ADD CONSTRAINT "STAGES_STATUS_PK" PRIMARY KEY ("OSS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."OPP_STAGES_STATUS" MODIFY ("OSS_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."OPP_STAGES_STATUS" MODIFY ("OSS_DISPLAY_ORDER" NOT NULL ENABLE);
