--------------------------------------------------------
--  Ref Constraints for Table OPPORTUNITIES
--------------------------------------------------------

  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK1" FOREIGN KEY ("OPP_CONTRACT_TYPE")
	  REFERENCES "PRJ"."PRJ_CONTRACT_TYPES" ("ID") ENABLE;
  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK2" FOREIGN KEY ("OPP_REFERENCE_TO_PIPELINE")
	  REFERENCES "PRJ"."LGS_CONTRACTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK3" FOREIGN KEY ("OPP_STATUS")
	  REFERENCES "PRJ"."OPP_STATUS" ("OPS_CODE") ENABLE;
  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK4" FOREIGN KEY ("OPP_STAGE")
	  REFERENCES "PRJ"."OPP_STAGES" ("OST_CODE") ENABLE;
  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK5" FOREIGN KEY ("OPP_STAGE_STATUS")
	  REFERENCES "PRJ"."OPP_STAGES_STATUS" ("OSS_CODE") ENABLE;
  ALTER TABLE "PRJ"."OPPORTUNITIES" ADD CONSTRAINT "OPPORTUNITIES_FK6" FOREIGN KEY ("OPP_CRY")
	  REFERENCES "PRJ"."PRJ_CURRENCIES" ("ID") ENABLE;
