--------------------------------------------------------
--  Constraints for Table PRJ_ENROLLED_DETS_BAK1
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK1" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK1" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK1" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK1" MODIFY ("NO_OF_HOURS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK1" MODIFY ("EMPLOYEE" NOT NULL ENABLE);
