--------------------------------------------------------
--  Constraints for Table PRJ_WBS_DEPENDENCIES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" ADD CONSTRAINT "PRJ_WBS_DEPENDENCI_ROW_KEY_UNQ" UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" ADD CONSTRAINT "PRJ_WBS_DEPENDENCI_WBD_ID_PK" PRIMARY KEY ("WBD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("ROW_KEY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("WBD_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
