--------------------------------------------------------
--  Constraints for Table PRJ_DELETED_ENROLLED_DETS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_DELETED_ENROLLED_DETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ENROLLED_DETS" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ENROLLED_DETS" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ENROLLED_DETS" MODIFY ("NO_OF_HOURS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ENROLLED_DETS" MODIFY ("EMPLOYEE" NOT NULL ENABLE);
