--------------------------------------------------------
--  Constraints for Table PRJ_WBS_DOCS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" ADD CONSTRAINT "PRJ_WBS_DOCS_ROW_KEY_UNQ" UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" ADD CONSTRAINT "PRJ_WBS_DOCS_WBC_ID_PK" PRIMARY KEY ("WBC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("ROW_KEY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("WBC_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_DOCS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
