--------------------------------------------------------
--  Constraints for Table PRJ_INVOICES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_INVOICES" ADD CONSTRAINT "PRJ_INVOICES_PK" PRIMARY KEY ("INV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_INVOICES" MODIFY ("INV_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_INVOICES" MODIFY ("INV_PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_INVOICES" MODIFY ("INV_PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_INVOICES" MODIFY ("INV_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_INVOICES" MODIFY ("INV_INVOICE_NUMBER" NOT NULL ENABLE);
