--------------------------------------------------------
--  Constraints for Table PRJ_GRADE_PRICES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" ADD CONSTRAINT "GRDPR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" ADD CONSTRAINT "GRDPR_UK" UNIQUE ("DSP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" MODIFY ("DSP_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" MODIFY ("E_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_GRADE_PRICES" MODIFY ("START_DATE" NOT NULL ENABLE);
