--------------------------------------------------------
--  Constraints for Table PRJ_ENROLLED_DETS_BAK
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK" MODIFY ("NO_OF_HOURS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS_BAK" MODIFY ("EMPLOYEE" NOT NULL ENABLE);
