--------------------------------------------------------
--  Constraints for Table PRJ_PROJECTWORK_TYPES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_PROJECTWORK_TYPES" ADD CONSTRAINT "PRJWORK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 655360 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_PROJECTWORK_TYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECTWORK_TYPES" MODIFY ("ESTIMATED_DAYS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECTWORK_TYPES" MODIFY ("WRKTYP_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECTWORK_TYPES" MODIFY ("PROJ_ID" NOT NULL ENABLE);
