--------------------------------------------------------
--  Constraints for Table PRJ_CURRENCY_RATES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_CURRENCY_RATES" ADD CONSTRAINT "PRJ_CURRENCY_RATES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_CURRENCY_RATES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_CURRENCY_RATES" MODIFY ("CURRENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_CURRENCY_RATES" MODIFY ("RATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_CURRENCY_RATES" MODIFY ("DAY" NOT NULL ENABLE);
