--------------------------------------------------------
--  Constraints for Table PRJ_PROJECT_STATUS_HISTORY
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" ADD CONSTRAINT "PRJ_PROJECT_STATUS_HISTORY_PK" PRIMARY KEY ("PSH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" MODIFY ("PSH_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" MODIFY ("PSH_PRJ_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" MODIFY ("PSH_STS_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" MODIFY ("PSH_DATE" NOT NULL ENABLE);
