--------------------------------------------------------
--  Constraints for Table PRJ_OUTCOME_TYPES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" ADD CONSTRAINT "PRJ_OUTCOME_TYPES_POT_ID_PK" PRIMARY KEY ("POT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" ADD CONSTRAINT "PRJ_OUTCOME_TYPES_ROW_KEY_UNQ" UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("ROW_KEY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("POT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_OUTCOME_TYPES" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
