--------------------------------------------------------
--  Ref Constraints for Table PRJ_PROJECT_STATUS_HISTORY
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" ADD CONSTRAINT "PRJ_PROJECT_STATUS_HISTOR_FK1" FOREIGN KEY ("PSH_PRJ_ID")
	  REFERENCES "PRJ"."LGS_PROJECTS" ("ID") DISABLE;
  ALTER TABLE "PRJ"."PRJ_PROJECT_STATUS_HISTORY" ADD CONSTRAINT "PRJ_PROJECT_STATUS_HISTOR_FK2" FOREIGN KEY ("PSH_STS_ID")
	  REFERENCES "PRJ"."PRJ_STATUS" ("PST_ID") ENABLE;
