--------------------------------------------------------
--  Constraints for Table PRJ_DELETED_ESTIMATED_DETS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_DELETED_ESTIMATED_DETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ESTIMATED_DETS" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ESTIMATED_DETS" MODIFY ("NO_OF_DAYS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_ESTIMATED_DETS" MODIFY ("SCALE" NOT NULL ENABLE);
