--------------------------------------------------------
--  Ref Constraints for Table PRJ_WBS_ASSIGNEES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIGNE_WBA_EMP_ID_FK" FOREIGN KEY ("WBA_EMP_ID")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIGNE_WBA_STATUS_FK" FOREIGN KEY ("WBA_STATUS")
	  REFERENCES "PRJ"."PRJ_STATUS" ("PST_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIGNE_WBA_TASK_ID_FK" FOREIGN KEY ("WBA_TASK_ID")
	  REFERENCES "PRJ"."PRJ_WBS" ("WBS_ID") ON DELETE CASCADE ENABLE;
