--------------------------------------------------------
--  Ref Constraints for Table PRJ_EXPENCES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_EXPENCES" ADD CONSTRAINT "PRJ_EXPENCESCONTRACTS_FK" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "PRJ"."LGS_CONTRACTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."PRJ_EXPENCES" ADD CONSTRAINT "PRJ_EXPENCESCURRENCY_FK" FOREIGN KEY ("CURRENCY")
	  REFERENCES "PRJ"."PRJ_CURRENCIES" ("ID") ENABLE;
  ALTER TABLE "PRJ"."PRJ_EXPENCES" ADD CONSTRAINT "PRJ_EXPENCESEMPLOYEE_FK" FOREIGN KEY ("EMPLOYEE_CODE")
	  REFERENCES "PRJ"."PRJ_EMPLOYEE_SALARY" ("EMP_CODE") ENABLE;
  ALTER TABLE "PRJ"."PRJ_EXPENCES" ADD CONSTRAINT "PRJ_EXPENCESPROJECTS_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PRJ"."LGS_PROJECTS" ("ID") ENABLE;
  ALTER TABLE "PRJ"."PRJ_EXPENCES" ADD CONSTRAINT "PRJ_EXPENCESPROJECTWORKT_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "PRJ"."PRJ_PROJECTWORK_TYPES" ("ID") ENABLE;
