--------------------------------------------------------
--  Constraints for Table PRJ_ESTIMATED_DETS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_ESTIMATED_DETS" ADD CONSTRAINT "PRJ_ESTIMATED_DETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_ESTIMATED_DETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ESTIMATED_DETS" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ESTIMATED_DETS" MODIFY ("NO_OF_DAYS" NOT NULL DISABLE);
  ALTER TABLE "PRJ"."PRJ_ESTIMATED_DETS" MODIFY ("SCALE" NOT NULL ENABLE);
