--------------------------------------------------------
--  Ref Constraints for Table PRJ_WBS_OUTCOMES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS_OUTCOMES" ADD CONSTRAINT "PRJ_WBS_OUTCOME_WBO_POT_ID_FK" FOREIGN KEY ("WBO_POT_ID")
	  REFERENCES "PRJ"."PRJ_OUTCOME_TYPES" ("POT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_OUTCOMES" ADD CONSTRAINT "PRJ_WBS_OUTCO_PRJ_WBS_ASSIG_FK" FOREIGN KEY ("PRJ_WBS_ASSIGNEE_ID")
	  REFERENCES "PRJ"."PRJ_WBS_ASSIGNEES" ("WBA_ID") ON DELETE CASCADE ENABLE;
