--------------------------------------------------------
--  Constraints for Table PRJ_WBS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS" ADD CONSTRAINT "PRJ_WBS_ROW_KEY_UNQ" UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS" ADD CONSTRAINT "PRJ_WBS_WBS_COMPLETION_PER_BET" CHECK (wbs_completion_percentage between 0 and 100) ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS" ADD CONSTRAINT "PRJ_WBS_WBS_ID_PK" PRIMARY KEY ("WBS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("ROW_KEY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("WBS_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
