--------------------------------------------------------
--  Constraints for Table PRJ_SALARY_GRADES_HISTORY
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_SALARY_GRADES_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_SALARY_GRADES_HISTORY" MODIFY ("FROM_SALARY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_SALARY_GRADES_HISTORY" MODIFY ("TO_SALARY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_SALARY_GRADES_HISTORY" MODIFY ("GRADE_PRICE_ID" NOT NULL ENABLE);
