--------------------------------------------------------
--  Constraints for Table PRJ_EMPLOYEE_SALARY_HISTORY
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY_HISTORY" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY_HISTORY" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY_HISTORY" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY_HISTORY" MODIFY ("SALARY_GRADE_ID" NOT NULL ENABLE);
