--------------------------------------------------------
--  Constraints for Table PRJ_ENROLLED_DETS
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" ADD CONSTRAINT "PRJ_ENROLLED_DETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" MODIFY ("PROJECT_WORKTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" MODIFY ("NO_OF_HOURS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_ENROLLED_DETS" MODIFY ("EMPLOYEE" NOT NULL ENABLE);
