--------------------------------------------------------
--  Constraints for Table PRJ_DELETED_PRJ_WORK_TYPES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_DELETED_PRJ_WORK_TYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_PRJ_WORK_TYPES" MODIFY ("ESTIMATED_DAYS" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_PRJ_WORK_TYPES" MODIFY ("WRKTYP_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_DELETED_PRJ_WORK_TYPES" MODIFY ("PROJ_ID" NOT NULL ENABLE);
