--------------------------------------------------------
--  Constraints for Table PRJ_WBS_ASSIGNEES
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIGNEES_ROW_KEY_UNQ" UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIGNEES_WBA_ID_PK" PRIMARY KEY ("WBA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" ADD CONSTRAINT "PRJ_WBS_ASSIG_WBA_COMPLEAT_BET" CHECK (wba_compleation_percentage between 0 and 100) ENABLE;
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("ROW_KEY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("WBA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_WBS_ASSIGNEES" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
