--------------------------------------------------------
--  Constraints for Table PRJ_EMPLOYEE_SALARY
--------------------------------------------------------

  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" ADD CONSTRAINT "EMPSAL_PK" PRIMARY KEY ("EMP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" MODIFY ("SALARY_GRADE_ID" NOT NULL ENABLE);
